apiVersion: v1
kind: Service
metadata:
  name: {{ include "xapp-qos-xslice.fullname" . }}-http
  labels:
    {{- include "xapp-qos-xslice.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "xapp-qos-xslice.fullname" . }}
  ports:
    - name: http-health
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
    - name: http-metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.metricsPort }}
