# =============================================================================
# srsUE Configuration - ZeroMQ Virtual RF Mode
# Arquivo: configs/testbed_zmq/ue_srsran_zmq.conf
# =============================================================================

[rf]
device_name = zmq
device_args = tx_port=tcp://127.0.0.1:2001,rx_port=tcp://127.0.0.1:2000,base_srate=23.04e6

[usim]
mode = soft
imsi = 999700000000001
milenage = true
k = 465B5CE8B199B49FAA5F0A2EE238A6BC
opc = E8ED289DEBA952E4283B54E88E6183CA

[nas]
apn = internet
apn_protocol = ipv4

[gw]
netns = uens1
ip_devname = uesimtun0
ip_netmask = 255.255.0.0

[log]
all_level = warning
nas_level = info
rrc_level = info
