"""
Constantes e Códigos de Procedimento do E2 Application Protocol (E2AP v02.03 / v03.00)
Conforme especificação normativa O-RAN.WG3.E2AP e O-RAN Software Community.
"""

# Message Types RMR (O-RAN SC Convention)
RIC_SUBSCRIPTION_REQ = 12010
RIC_SUBSCRIPTION_RESP = 12011
RIC_SUBSCRIPTION_FAILURE = 12012
RIC_SUBSCRIPTION_DELETE_REQ = 12020
RIC_SUBSCRIPTION_DELETE_RESP = 12021
RIC_SUBSCRIPTION_DELETE_FAILURE = 12022

RIC_CONTROL_REQ = 12010
RIC_CONTROL_ACK = 12011
RIC_CONTROL_FAILURE = 12012

RIC_INDICATION = 12050

RDL_ACTION_PROPOSAL = 30000

# Procedimentos E2AP Elementares (Elementary Procedures)
PROC_RIC_SUBSCRIPTION = 201
PROC_RIC_SUBSCRIPTION_DELETE = 202
PROC_RIC_CONTROL = 204
PROC_RIC_INDICATION = 205
PROC_E2_SETUP = 1
PROC_RESET = 3

# IDs de Protocol IE Padronizados E2AP
IE_RIC_REQUEST_ID = 29
IE_RAN_FUNCTION_ID = 5
IE_RIC_SUBSCRIPTION_DETAILS = 30
IE_RIC_ACTION_ADMITTED_LIST = 17
IE_RIC_ACTION_NOT_ADMITTED_LIST = 18
IE_RIC_INDICATION_HEADER = 25
IE_RIC_INDICATION_MESSAGE = 26
IE_RIC_INDICATION_SN = 27
IE_RIC_INDICATION_TYPE = 28
IE_RIC_CALL_PROCESS_ID = 20
IE_RIC_CONTROL_HEADER = 22
IE_RIC_CONTROL_MESSAGE = 23
IE_RIC_CONTROL_ACK_REQUEST = 21
IE_RIC_CONTROL_OUTCOME = 32
IE_CAUSE = 1
IE_CRITICALITY_DIAGNOSTICS = 2

# Criticalities
CRITICALITY_REJECT = 0
CRITICALITY_IGNORE = 1
CRITICALITY_NOTIFY = 2
