apiVersion: v1
kind: Service
metadata:
  name: {{ include "iqos-xapp-rdl.fullname" . }}-rmr
  labels:
    {{- include "iqos-xapp-rdl.labels" . | nindent 4 }}
spec:
  type: {{ if and .Values.service .Values.service.rmr }}{{ .Values.service.rmr.type | default "ClusterIP" }}{{ else }}ClusterIP{{ end }}
  ports:
    - port: {{ if and .Values.service .Values.service.rmr }}{{ .Values.service.rmr.dataPort | default 4560 }}{{ else }}4560{{ end }}
      targetPort: {{ if and .Values.service .Values.service.rmr }}{{ .Values.service.rmr.dataPort | default 4560 }}{{ else }}4560{{ end }}
      protocol: TCP
      name: rmr-data
    - port: {{ if and .Values.service .Values.service.rmr }}{{ .Values.service.rmr.routePort | default 4561 }}{{ else }}4561{{ end }}
      targetPort: {{ if and .Values.service .Values.service.rmr }}{{ .Values.service.rmr.routePort | default 4561 }}{{ else }}4561{{ end }}
      protocol: TCP
      name: rmr-route
  selector:
    {{- include "iqos-xapp-rdl.selectorLabels" . | nindent 4 }}
