apiVersion: v1
kind: Service
metadata:
  name: {{ include "iqos-xapp-rdl.fullname" . }}-http
  labels:
    {{- include "iqos-xapp-rdl.labels" . | nindent 4 }}
spec:
  type: {{ if and .Values.service .Values.service.http }}{{ .Values.service.http.type | default "ClusterIP" }}{{ else }}ClusterIP{{ end }}
  ports:
    - port: {{ if and .Values.service .Values.service.http }}{{ .Values.service.http.port | default 8080 }}{{ else }}8080{{ end }}
      targetPort: {{ if and .Values.service .Values.service.http }}{{ .Values.service.http.targetPort | default 8080 }}{{ else }}8080{{ end }}
      protocol: TCP
      name: http-health
    - port: {{ if and .Values.service .Values.service.metrics }}{{ .Values.service.metrics.port | default 8081 }}{{ else if and .Values.service .Values.service.http .Values.service.http.metricsPort }}{{ .Values.service.http.metricsPort }}{{ else }}8081{{ end }}
      targetPort: {{ if and .Values.service .Values.service.metrics }}{{ .Values.service.metrics.targetPort | default 8081 }}{{ else if and .Values.service .Values.service.http .Values.service.http.metricsPort }}{{ .Values.service.http.metricsPort }}{{ else }}8081{{ end }}
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "iqos-xapp-rdl.selectorLabels" . | nindent 4 }}
