apiVersion: v1
kind: Service
metadata:
  name: service-ricxapp-iqos-xapp-rdl-rmr
  namespace: ricxapp
  labels:
    app: iqos-xapp-rdl
    app.kubernetes.io/name: iqos-xapp-rdl
    app.kubernetes.io/part-of: openran-br-blueprint-v3
spec:
  type: ClusterIP
  selector:
    app: iqos-xapp-rdl
  ports:
    - name: rmr-data
      port: 4560
      targetPort: 4560
      protocol: TCP
    - name: rmr-route
      port: 4561
      targetPort: 4561
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: service-ricxapp-iqos-xapp-rdl-http
  namespace: ricxapp
  labels:
    app: iqos-xapp-rdl
    app.kubernetes.io/name: iqos-xapp-rdl
    app.kubernetes.io/part-of: openran-br-blueprint-v3
spec:
  type: ClusterIP
  selector:
    app: iqos-xapp-rdl
  ports:
    - name: http-health
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: metrics
      port: 8081
      targetPort: 8081
      protocol: TCP
