apiVersion: v2
name: iqos-xapp-rdl
description: xApp RDL Fase 2 - Context-Aware Resource and Decision Layer com MARL / MAPPO no Near-RT RIC O-RAN
type: application
version: 2.0.0
appVersion: "2.0.0"
keywords:
  - oran
  - near-rt-ric
  - xapp
  - rdl
  - marl
  - mappo
maintainers:
  - name: OpenRAN Engineering Team
    email: support@oran-rdl.org
