apiVersion: v1
kind: Namespace
metadata:
  name: ricplt
  labels:
    app.kubernetes.io/part-of: o-ran-sc
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ricxapp
  labels:
    app.kubernetes.io/part-of: o-ran-sc
    istio-injection: enabled
