apiVersion: v1
kind: Service
metadata:
  name: ricxapp-iqos-xapp-rdl-rmr
  namespace: ricxapp
  labels:
    app: ricxapp-iqos-xapp-rdl
spec:
  type: ClusterIP
  selector:
    app: ricxapp-iqos-xapp-rdl
  ports:
  - name: rmr-data
    port: 4560
    targetPort: 4560
    protocol: TCP
  - name: rmr-route
    port: 4561
    targetPort: 4561
    protocol: TCP
