apiVersion: v1
kind: Service
metadata:
  name: ricxapp-iqos-xapp-rdl-http
  namespace: ricxapp
  labels:
    app: ricxapp-iqos-xapp-rdl
spec:
  type: ClusterIP
  selector:
    app: ricxapp-iqos-xapp-rdl
  ports:
  - name: http-health
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: http-metrics
    port: 8081
    targetPort: 8081
    protocol: TCP
